language: cpp
os: linux

matrix:
  # GCC
  include:
    - env: C_COMPILER=gcc-7 CXX_COMPILER=g++-7
      addons:
        apt:
          sources:
           - ubuntu-toolchain-r-test
          packages:
           - g++-7

    - env: C_COMPILER=gcc-8 CXX_COMPILER=g++-8
      addons:
        apt:
          sources:
           - ubuntu-toolchain-r-test
          packages:
           - g++-8

    - env: C_COMPILER=gcc-9 CXX_COMPILER=g++-9
      addons:
        apt:
          sources:
           - ubuntu-toolchain-r-test
          packages:
           - g++-9

    - env: C_COMPILER=clang-5.0 CXX_COMPILER=clang++-5.0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-5.0
          packages:
            - clang-5.0

    - env: C_COMPILER=clang-6.0 CXX_COMPILER=clang++-6.0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-6.0
          packages:
            - clang-6.0

    - env: C_COMPILER=clang-7 CXX_COMPILER=clang++-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-7
          packages:
            - clang-7

    - env: C_COMPILER=clang-8 CXX_COMPILER=clang++-8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-8
          packages:
            - clang-8

    - env: C_COMPILER=clang-9 CXX_COMPILER=clang++-9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-9
          packages:
            - clang-9

install:
  - export CC=${C_COMPILER}
  - export CXX=${CXX_COMPILER}

before_script:
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=MinSizeRel

script:
  - cmake --build . -- -j2
  - ctest --output-on-failure -j2
