language: cpp
os: linux

matrix:
  # GCC
  include:
    - env: C_COMPILER=gcc-7 CXX_COMPILER=g++-7
      addons:
        apt:
          sources:
           - ubuntu-toolchain-r-test
          packages:
           - g++-7

    - env: C_COMPILER=clang-4.0 CXX_COMPILER=clang++-4.0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0

    - env: C_COMPILER=clang-5.0 CXX_COMPILER=clang++-5.0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0

install:
  - export CC=${C_COMPILER}
  - export CXX=${CXX_COMPILER}

before_script:
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=MinSizeRel

script:
  - cmake --build . -- -j2
  - ctest --output-on-failure -j2
